#!/usr/bin/env ruby
# -*- coding: utf-8 -*-
#
# ltsvデータをJSONに変換
#
curindent = -1
ARGF.each { |line|
  line.chomp!
  next if line == ''
  line.sub!(/^(\s*)/,'')
  indent = $&.length
  if indent > curindent then
    # puts (curindent == 0 ? "" : ("  " * (indent+0) + "children: ")) + "[\n" + "  " * (indent+0) + "{"
    print indent == 0 ? "" : ("  " * indent + "children: ")
    puts "[\n" + "  " * (indent+0) + "{"
    curindent = indent
  elsif indent < curindent then
    while indent < curindent do
      puts "  " * (indent+1) + "}]\n" + "  " * (indent+0) + "},\n" + "  "*(indent+0) + "{"
      curindent -= 1
    end
  else
    puts "  " * (indent+0) + "},\n" + "  "*(indent+0) + "{"
  end
  line.split(/\t/).each { |entry|
    entry =~ /^([a-zA-Z_]+):(\s*)(.*)$/
    key = $1
    value = $3
    puts "  " * (curindent+1) + "#{key}: '#{value}',"
  }
}
while 0 <= curindent do
  puts "  " * (curindent) + "}]\n"
  curindent -= 1
end


